name: Site Reliability
on: 
  workflow_dispatch:
  push:
    branches: 
      - main
  schedule:
    # * is a special character in YAML so you have to quote this string
    - cron:  '0 4 * * *'
jobs:
  crawl_for_broken_links:
    runs-on: ubuntu-latest
    name: Broken-Links-Crawler
    steps:
    - name: Debug Action
      uses: hmarr/debug-action@v1.0.0
    - name: Checking links
      id: checking
      uses: ScholliYT/Broken-Links-Crawler-Action@v3
      with:
        website_url: 'https://cute-valkyrie-f9ee5a.netlify.app'
        exclude_url_prefix: 'mailto:'
        verbose: 'true'
        max_retry_time: 30
        max_retries: 5